-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 05:16:30 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema novelizer
-- -----------------------------------------------------
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema novelizer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `novelizer`;

CREATE SCHEMA IF NOT EXISTS `novelizer` DEFAULT CHARACTER SET utf8 ;

USE `novelizer` ;

-- -----------------------------------------------------
-- Table `novelizer`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`action` (
  `action_id`  INT NOT NULL DEFAULT 0,
  `action_type` VARCHAR(10) NULL DEFAULT NULL,
  `character_id` INT NULL DEFAULT '0',
  `preset_id` INT NULL DEFAULT '0',
  `option_id` INT NULL DEFAULT '0',
  `posX` FLOAT NULL DEFAULT '0.0',
  `posY` FLOAT NULL DEFAULT '0.0',
  `animation` VARCHAR(50) DEFAULT NULL,
  `text` TEXT(500) DEFAULT NULL,  
  `block_id` INT NOT NULL,
  PRIMARY KEY (`action_id`,`block_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `novelizer`.`block`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`block` (
  `block_id`  INT NOT NULL DEFAULT 0,
  `next_block_id` INT NULL DEFAULT '0',
  `scene_id` INT NOT NULL,
  PRIMARY KEY (`block_id`,`scene_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`project` (
  `project_id`  INT NOT NULL DEFAULT 0,
  `project_name` VARCHAR(45) NULL,
  `project_info` TEXT(500) NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`scene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`scene` (
  `scene_id` INT NOT NULL DEFAULT 0,
  `project_id` INT NOT NULL,
  `start_block_id` INT NULL,
  `scene_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`scene_id`,`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `novelizer`.`USERS` (
  `userId` VARCHAR(20) NOT NULL DEFAULT 0,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
