-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 16:02:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema novelizer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema novelizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `novelizer` DEFAULT CHARACTER SET utf8 ;
USE `novelizer` ;

-- -----------------------------------------------------
-- Table `novelizer`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`action` (
  `action_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NULL DEFAULT NULL,
  `option_data` TEXT NULL DEFAULT NULL,
  `block_id` INT(11) NOT NULL,
  PRIMARY KEY (`actionId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`background`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`background` (
  `action_id` INT(11) NOT NULL,
  `preset_id` INT(11) NOT NULL,
  `option` VARCHAR(10) NOT NULL,
  `position` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`actionId`),
  INDEX `fk_background_action1_idx` (`actionId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`block`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`block` (
  `block_id` INT(11) NOT NULL AUTO_INCREMENT,
  `next_block_id` INT(11) NULL DEFAULT '0',
  `scene_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`blockId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`charater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`charater` (
  `action_id` INT(11) NOT NULL,
  `preset_id` INT(11) NOT NULL,
  `option` VARCHAR(10) NOT NULL,
  `position` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`actionId`),
  INDEX `fk_charater_action1_idx` (`actionId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`project` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`scene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`scene` (
  `scene_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NULL DEFAULT NULL,
  `scene_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sceneId`),
  INDEX `fk_scene_project1_idx` (`project_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `novelizer`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novelizer`.`text` (
  `action_id` INT(11) NOT NULL,
  `character_id` VARCHAR(10) NOT NULL,
  `text` TEXT NOT NULL,
  `option` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`action_id`),
  INDEX `fk_text_action1_idx` (`action_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
